---
title: "03_01_Process_by_pca"
author: "Et al"
date: "27/5/2022"
output: html_document
---

#1. Librerías

```{r}
library(tidyverse)
library(gridExtra)
#library(devtools)
#install_github("vqv/ggbiplot")
library(ggbiplot)
```


#2. Directorio

```{r}
main   <- "C:/Users/braul/Desktop/02_projects/01_GITHUB/Excess_Mort/03_Second_Stage/Generate database" 
input  <- paste(main, sep = "", "/1.pca/01_DB")
output <- paste(main, sep = "", "/1.pca/02_output")
```


#3. Importación

```{r,message=F,warning=F,eval=F}

source("excess_functions.R")
library(tidyverse)
####
# Provincial
social.dets  <- readRDS(file.path(input,"vulnr_df_prov.rds"))         %>% 
                dplyr::rename(pr_insu       = INEI_prop_aseg_2017,                 # insurance
                       pr_edu_inf_25       = INEI_prop_niv.insInf_25yrs,
                       pr_pov_2018         = prop_pobreza_2018,                    # poverty
                       pr_wout_water       = INEI_prop_NoAbsAguVvn_int_2017,       # prp de pob wihout  water
                       pr_urban_2017       = INEI_prop_urbano_2017,                #  prp of urban pop 
                       pr_one_hab          = Prop_1_hab,                           # prp de casas 1hab
                       pr_with_elec        = INEI_Prop_NoAlumbradoElectri_2017,    # prp de pob wihout electricity
                       pr_wrk_oth_distr    = INEI_prop_cntr_trb_otroDistrito_2017, # prp of pop working in other district 
                       pr_liv_oth_distr    = INEI_prop_NoViviaDistr5_2017,         # mudados
                       pr_edu_oth_distr    = INEI_prop_Inst.Edu_EnOtroDistrito_2017,
                       pr_NBI              = NBI_Prop,                             # prp con al menos min 1 necesidad insatisfecha
                       min_tercer          = `Tertiary HCF`,
                       min_second          = `Secondary HCF`,
                       min_prim            = `Primary HCF`,
                       pr_no_bl_mz         = INEI_prop_autoident_NoMstBlc,
                       pr_no_inter         = INEI_prop_NoInternet_2017,
                       pr_no_tele          = INEI_prop_NoTelevisor_2017,
                       pr_no_cel           = INEI_prop_NoCelular_2017,
                       pr_si_buscajob      = INEI_prop_si_buscando_trabajo,
                       pr_no_trabajo_pago  = INEI_prop_no_trabajo_pago,
                       pr_no_casa_titu     = INEI_prop_Notenenciaviv_2017,
                       pr_no_vehiculo      = INEI_prop_novehiculo_2017
                       
                # Education and demographic dimension
                # Dimensión económica con variables estandarizadas
                ) %>% 
                mutate( education_dim     = as.numeric(scale.default(pr_edu_inf_25)),
                        demographics_dim  = as.numeric(scale.default(pr_no_bl_mz)),
                        economic_dim_3    = as.numeric(scale.default(pr_insu)),
                        economic_dim_4    = as.numeric(scale.default(pr_pov_2018)),
                        economic_dim_5    = as.numeric(scale.default(pr_NBI))
                ) %>% 
                left_join(readRDS(file.path(main,"geo_measure.rds"))    %>% dplyr::rename(dep = reg), by = c("dep" = "dep", "prov" = "prov") ) %>% 
                left_join(readRDS(file.path(main,"economics_2017.rds")) %>% dplyr::rename(dep = reg), by = c("dep" = "dep", "prov" = "prov", "ubigeo" = "ubigeo"))

                                                                    

####################################################
# departamental 
social.dets.dep <- readRDS(file.path(input,"social_dets_dep.rds"))               %>% 
                   select(dep,Endes_Prop_Diab,Endes_Prop_Fuma_Diario,
                        Endes_Prop_HA,ENDES_prop_Obes,Endes_Prop_Tos,
                        Enfermeras_10khab,Farmaceuticos_10khab,
                        TecMedicos_10khab,
                        Medicos_10khab,Presupuesto_salud,Presupuesto_publico, 
                        Pob_T_Int, Prop_vuelos_entrantes, PBI_per_capita, Prop_neu, MMR, Muertes_materna, mortalidad_prop_cancer )     %>% 
            dplyr::rename(pr_diab               = Endes_Prop_Diab,
                          pr_smoke              = Endes_Prop_Fuma_Diario,
                          pr_hyper_tension      = Endes_Prop_HA,
                          pr_obes               = ENDES_prop_Obes,
                          pr_tos                = Endes_Prop_Tos,
                          med_x_100             = Medicos_10khab)                   %>% 
                   mutate(med_x_100             = med_x_100/10,  
                          enf_x_100             = Enfermeras_10khab/10,
                          far_x_100             = Farmaceuticos_10khab/10,
                        tecmed_x_100          = TecMedicos_10khab/10,
                        pr_salud_presupuesto  = Presupuesto_salud/Presupuesto_publico,
                        
                        #Dimensión salud con variables estandarizadas
                        
                        health_population_status_dim_3  = as.numeric(scale.default(pr_diab)),
                        health_population_status_dim_4  = as.numeric(scale.default(pr_obes)),  
                        health_population_status_dim_5  = as.numeric(scale.default(pr_tos)),
                        health_population_status_dim_10 = as.numeric(scale.default(pr_hyper_tension)),
                        health_population_status_dim_11 = as.numeric(scale.default(Prop_neu)),
                        health_population_status_dim_12 = as.numeric(scale.default(MMR)),
                        health_population_status_dim_13 = as.numeric(scale.default(Muertes_materna)),
                        health_population_status_dim_14 = as.numeric(scale.default(mortalidad_prop_cancer)),
                        health_system_status_dim_3      = as.numeric(scale.default(med_x_100)),
                        health_system_status_dim_4      = as.numeric(scale.default(enf_x_100)),
                        health_system_status_dim_5      = as.numeric(scale.default(far_x_100)),
                        health_system_status_dim_6      = as.numeric(scale.default(pr_salud_presupuesto))
                        )

####################################################

```


# 4. Principal components analysis

```{r,message=F,warning=F}

# variables , componentes , dimensiones 

dynamic.population.pca_1             <- prcomp(social.dets     %>%
                                        select(pr_edu_oth_distr,pr_wrk_oth_distr,
                                        pr_liv_oth_distr), center = TRUE,scale. = TRUE)

dynamic.population.pca_2             <- prcomp(social.dets     %>% 
                                        select(pr_edu_oth_distr, pr_wrk_oth_distr,
                                        pr_no_vehiculo), center = TRUE,scale. = TRUE) 

dynamic.population.pca_3             <- prcomp(  
                                        left_join( social.dets     %>% select(dep, prov, pr_edu_oth_distr, pr_wrk_oth_distr),
                                                   social.dets.dep %>% select(dep, Prop_vuelos_entrantes), by = c("dep" = "dep") ) %>% select(-c(dep, prov)),
                                        center = TRUE, scale. = TRUE)

economic.pca_1                       <- prcomp(social.dets     %>% 
                                        select(pr_insu, pr_pov_2018), center = TRUE,scale. = TRUE) 

economic.pca_2                       <- prcomp(social.dets     %>% 
                                        select(pr_insu, pr_pov_2018, pr_no_trabajo_pago), center = TRUE,scale. = TRUE) 

economic.pca_6                       <- prcomp(social.dets     %>% 
                                        select(pr_pov_2018, pr_NBI), center = TRUE,scale. = TRUE) 

economic.pca_7                       <- prcomp(  
                                        left_join( social.dets     %>% select(dep, prov, pr_insu, pr_pov_2018),
                                                   social.dets.dep %>% select(dep, PBI_per_capita), by = c("dep" = "dep") ) %>% select(-c(dep, prov)),
                                        center = TRUE, scale. = TRUE)

economic.pca_8                       <- prcomp(  
                                        left_join( social.dets     %>% select(dep, prov, pr_pov_2018),
                                                   social.dets.dep %>% select(dep, PBI_per_capita), by = c("dep" = "dep") ) %>% select(-c(dep, prov)),
                                        center = TRUE, scale. = TRUE)

economic.pca_9                       <- prcomp(social.dets     %>% 
                                        select(pr_insu, pr_pov_2018, PIBpc, employment), center = TRUE,scale. = TRUE) 

economic.pca_10                       <- prcomp(social.dets     %>% 
                                        select(pr_pov_2018, PIBpc), center = TRUE,scale. = TRUE) 



house.characteristics.pca_1          <- prcomp(social.dets     %>% 
                                        select(INEI_prop_Nopared_ladrillo_cemento, INEI_prop_No_techo_concreto,   
                                               INEI_prop_Nopiso_cemento_loseta), center = TRUE,scale. = TRUE)

house.characteristics.pca_2          <- prcomp(social.dets     %>% 
                                        select(INEI_prop_Nopared_ladrillo_cemento, INEI_prop_No_techo_concreto,   
                                               INEI_prop_Nopiso_cemento_loseta, pr_urban_2017), center = TRUE,scale. = TRUE)

health.pop.status.pca_1              <- prcomp(social.dets.dep %>% 
                                        select(pr_diab, pr_obes, pr_tos), center = TRUE,scale. = TRUE)

health.pop.status.pca_2              <- prcomp(social.dets.dep %>% 
                                        select(pr_diab, pr_obes, pr_tos, pr_smoke), center = TRUE,scale. = TRUE)

health.pop.status.pca_6              <- prcomp(social.dets.dep %>% 
                                        select(pr_tos, pr_smoke), center = TRUE,scale. = TRUE)

health.pop.status.pca_7              <- prcomp(social.dets.dep %>% 
                                        select(pr_tos, pr_obes), center = TRUE,scale. = TRUE)

health.pop.status.pca_8              <- prcomp(social.dets.dep %>% 
                                        select(pr_tos, pr_diab), center = TRUE,scale. = TRUE)

health.pop.status.pca_9              <- prcomp(social.dets.dep %>% 
                                        select(pr_tos, pr_hyper_tension), center = TRUE,scale. = TRUE)


health.system.status.pca_1           <- prcomp(social.dets.dep %>% 
                                        select(med_x_100, enf_x_100,
                                               far_x_100), center = TRUE,scale. = TRUE)

health.system.status.pca_2           <- prcomp(social.dets.dep %>% 
                                        select(med_x_100, enf_x_100,
                                               pr_salud_presupuesto), center = TRUE,scale. = TRUE)


geographic.pca_1                    <- prcomp(social.dets     %>% 
                                       select(distance_qapac, distance_port, distance_airpot), center = TRUE,scale. = TRUE)

geographic.pca_2                    <- prcomp(social.dets     %>% 
                                       select(altitude, slope), center = TRUE,scale. = TRUE)

geographic.pca_3                    <- prcomp(social.dets     %>% 
                                       select(distance_port, slope), center = TRUE,scale. = TRUE)

geographic.pca_4                    <- prcomp(social.dets     %>% 
                                       select(distance_qapac, altitude), center = TRUE,scale. = TRUE)   

```



# 5. Number of dimensions

## 1) Population's dynamic

```{r,eval=F,message=F,warning=F}
library(gridExtra)
library(grid)

(VE <- dynamic.population.pca$sdev^2)
PVE <- VE / sum(VE)
round(PVE, 2)


PVEplot  <-  qplot(c(1:3), PVE) + 
             geom_line() + 
             xlab("Principal Component") + 
             ylab("PVE") +
             ggtitle("Scree Plot") +
             ylim(0, 1)

# Cumulative PVE plot
cumPVE   <- qplot(c(1:3), cumsum(PVE))       + 
            geom_line()                      + 
            xlab("Principal Component")      + 
            ylab(NULL)                       + 
            ggtitle("Cumulative Scree Plot") +
            ylim(0,1)

grid.arrange(PVEplot, cumPVE, ncol = 2)

```

## 2) Economics

```{r,eval=F,message=F,warning=F}
library(gridExtra)

(VE <- economic.pca$sdev^2)
PVE <- VE / sum(VE)
round(PVE, 2)


PVEplot  <-  qplot(c(1:3), PVE) +   # Adjust accord to dimension's number
             geom_line() + 
             xlab("Principal Component") + 
             ylab("PVE") +
             ggtitle("Scree Plot") +
             ylim(0, 1)

# Cumulative PVE plot
cumPVE   <- qplot(c(1:3), cumsum(PVE))       + 
            geom_line()                      + 
            xlab("Principal Component")      + 
            ylab(NULL)                       + 
            ggtitle("Cumulative Scree Plot") +
            ylim(0,1)

grid.arrange(PVEplot, cumPVE, ncol = 2)

```

## 3) Household characteristics

```{r,eval=F,message=F,warning=F}
library(gridExtra)

(VE <- house.characteristics.pca$sdev^2)
PVE <- VE / sum(VE)
round(PVE, 2)


PVEplot  <-  qplot(c(1:3), PVE) +   # Adjust accord to dimension's number
             geom_line() + 
             xlab("Principal Component") + 
             ylab("PVE") +
             ggtitle("Scree Plot") +
             ylim(0, 1)

# Cumulative PVE plot
cumPVE   <- qplot(c(1:3), cumsum(PVE))       + 
            geom_line()                      + 
            xlab("Principal Component")      + 
            ylab(NULL)                       + 
            ggtitle("Cumulative Scree Plot") +
            ylim(0,1)

grid.arrange(PVEplot, cumPVE, ncol = 2)
```




# 6. Selection variables

```{r,message=F,warning=F}
# obj: Max Proportion of Variance del primer componente 
# supuesto: el 1er componente es la dimension que queremos modelar 
# con al menos 3 variables maximizar 
summary(dynamic.population.pca_1)
summary(dynamic.population.pca_2)
summary(dynamic.population.pca_3)
summary(economic.pca_1)
summary(economic.pca_2)
summary(economic.pca_6)
summary(economic.pca_7)
summary(economic.pca_8)
summary(economic.pca_9)
summary(economic.pca_10)
summary(house.characteristics.pca_1)
summary(house.characteristics.pca_2)
summary(health.pop.status.pca_1)
summary(health.pop.status.pca_2)
summary(health.pop.status.pca_6)
summary(health.pop.status.pca_7)
summary(health.pop.status.pca_8)
summary(health.pop.status.pca_9)
summary(health.system.status.pca_1)
summary(health.system.status.pca_2)
summary(geographic.pca_1)
summary(geographic.pca_2)
summary(geographic.pca_3)
summary(geographic.pca_4)
```



# 7. Interpretation / biplot

## 1) Population's dynamic

```{r,message=F,warning=F,echo=F}
#########
ggbiplot(dynamic.population.pca)
dynamic.dimension       <- dynamic.population.pca$x
biplot(dynamic.population.pca, scale = 0)

# mean(dynamic.dimension)
# sd(dynamic.dimension)
#
# mean(economic.dimension)
# sd(economic.dimension)
# 
# mean(health.dimension)
# sd(health.dimension)

```

## 2) Economics

```{r,message=F,warning=F,echo=F}
ggbiplot(economic.pca)
economic.dimension <- economic.pca$x
biplot(economic.pca, scale = 0)
```


## 3) Household characteristics

```{r,message=F,warning=F,echo=F}
ggbiplot(house.characteristics.pca)
house.characteristics.dimension   <- house.characteristics.pca$x
biplot(house.characteristics.pca, scale = 0)
```


## 4) Health

```{r,message=F,warning=F,echo=F}
ggbiplot(health.performance.pca)
health.performance.dimension   <- health.performance.pca$x
biplot(health.performance.pca, scale = 0)

ggbiplot(health.status.pca)
health.status.dimension   <- health.status.pca$x
biplot(health.status.pca, scale = 0)
```

```{r}
dynamic.population.dim  <-  dynamic.population.pca$x %>% 
                            as.data.frame() %>% 
                            select(PC1) %>% 
                            dplyr::rename(dynamic.population.dim = PC1)
```



#8. Final database of determinants 

```{r,message=F,warning=F,echo=F}

# Componentes n =196 

dynamic_population_dim_1        <-  dynamic.population.pca_1$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(dynamic_population_dim_1  = PC1)

dynamic_population_dim_2        <-  dynamic.population.pca_2$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(dynamic_population_dim_2  = PC1)

dynamic_population_dim_3        <-  dynamic.population.pca_3$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(dynamic_population_dim_3  = PC1)


economic_dim_1                  <-  economic.pca_1$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(economic_dim_1  = PC1)

economic_dim_2                  <-  economic.pca_2$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(economic_dim_2  = PC1)

economic_dim_6                  <-  economic.pca_6$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(economic_dim_6  = PC1)

economic_dim_7                  <-  economic.pca_7$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(economic_dim_7  = PC1)

economic_dim_8                  <-  economic.pca_8$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(economic_dim_8  = PC1)

economic_dim_9                  <-  economic.pca_9$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(economic_dim_9  = PC1)

economic_dim_10                 <-  economic.pca_10$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(economic_dim_10  = PC1)


house_charact_dim_1             <-  house.characteristics.pca_1$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(house_charact_dim_1 = PC1)

house_charact_dim_2             <-  house.characteristics.pca_2$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(house_charact_dim_2 = PC1)



health_population_status_dim_1  <-  health.pop.status.pca_1$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_population_status_dim_1 = PC1)

health_population_status_dim_2  <-  health.pop.status.pca_2$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_population_status_dim_2 = PC1)

health_population_status_dim_6  <-  health.pop.status.pca_6$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_population_status_dim_6 = PC1)

health_population_status_dim_7  <-  health.pop.status.pca_7$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_population_status_dim_7 = PC1)

health_population_status_dim_8  <-  health.pop.status.pca_8$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_population_status_dim_8 = PC1)

health_population_status_dim_9  <-  health.pop.status.pca_9$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_population_status_dim_9 = PC1)



health_system_status_dim_1      <-  health.system.status.pca_1$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_system_status_dim_1 = PC1)

health_system_status_dim_2      <-  health.system.status.pca_2$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1)  %>% 
                                    dplyr::rename(health_system_status_dim_2 = PC1)


geographic_dim_1                <-  geographic.pca_1$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(geographic_dim_1  = PC1)

geographic_dim_2                <-  geographic.pca_2$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(geographic_dim_2  = PC1)

geographic_dim_3                <-  geographic.pca_3$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(geographic_dim_3  = PC1)

geographic_dim_4                <-  geographic.pca_4$x %>% 
                                    as.data.frame() %>% 
                                    select(PC1) %>% 
                                    dplyr::rename(geographic_dim_4  = PC1)


social.dets.pca <- left_join( cbind(social.dets, dynamic_population_dim_1, dynamic_population_dim_2, dynamic_population_dim_3, economic_dim_1, economic_dim_2, economic_dim_6,
                                    economic_dim_7, economic_dim_8, economic_dim_9, economic_dim_10, house_charact_dim_1, house_charact_dim_2, 
                                    geographic_dim_1, geographic_dim_2, geographic_dim_3, geographic_dim_4) ,
                              cbind(health_population_status_dim_1,health_population_status_dim_2, health_population_status_dim_6, health_population_status_dim_7, 
                                    health_population_status_dim_8, health_population_status_dim_9,     
                                    health_system_status_dim_1, health_system_status_dim_2, 
                                    social.dets.dep %>%  dplyr::select(dep, health_population_status_dim_3, health_population_status_dim_4, health_population_status_dim_5, health_population_status_dim_10,
                                                                       health_system_status_dim_3, health_system_status_dim_4, health_system_status_dim_5, health_system_status_dim_6) ) ,
                              by = c("dep" = "dep") ) %>% 
                   dplyr::select(dep, prov, 
                                 education_dim, demographics_dim, 
                                 dynamic_population_dim_1, dynamic_population_dim_2, dynamic_population_dim_3, 
                                 economic_dim_1, economic_dim_2, economic_dim_3, economic_dim_4, economic_dim_5, economic_dim_6, economic_dim_7, economic_dim_8, economic_dim_9, economic_dim_10,
                                 house_charact_dim_1, house_charact_dim_2,
                                 geographic_dim_1, geographic_dim_2, geographic_dim_3, geographic_dim_4,
                                 health_population_status_dim_1, health_population_status_dim_2, health_population_status_dim_3, health_population_status_dim_4,
                                 health_population_status_dim_5, health_population_status_dim_6, health_population_status_dim_7,
                                 health_population_status_dim_8, health_population_status_dim_9, health_population_status_dim_10,
                                 health_system_status_dim_1, health_system_status_dim_2, health_system_status_dim_3, 
                                 health_system_status_dim_4, health_system_status_dim_5, health_system_status_dim_6)
                            

saveRDS(social.dets.pca, file.path(output, "social_dets_pca.rds"))



# # left JOIN
# dim(health.status.dim)      # 25 
# dim(dynamic.population.dim) # 196 


# Puntos a tomar en cuenta  
# nueva base de datos de dimensiones  con n=196 , sugerencia   economic_dim_1 , economic_dim_2 
#  NOTA : dejar para la final la union entre los resultados pca  y la base de datos , caso contrario alteraras la estructura var-cov

```

`

# Final database

```{r,message=F,warning=F}

# "social.dets.pca"  . A este archivo es necesario introducirle las dimensiones de una sola variable ( estandarizacion de determinadas variables) , y probar nuevas variables . La estandarizacion si debe generar nuevas columnas en la bd final ejm econdim1 , econ_dim2, econ dim_3(pca de nbi y pobreza, nbi estandarizada , pobreza estandarizada). Asimismo las nuevas combinaciones solo son pruebas para ver si se puede mejorar la var explicada hasta el momento 
```




